name: realdrive
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.3.1
  location: ^8.0.0
  move_to_background: ^1.0.2
  flutter_local_notifications: ^18.0.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi_Black.otf
        - asset: fonts/Satoshi_BlackItalic.otf
        - asset: fonts/Satoshi_Bold.otf
        - asset: fonts/Satoshi_BoldItalic.otf
        - asset: fonts/Satoshi_Italic.otf
        - asset: fonts/Satoshi_Light.otf
        - asset: fonts/Satoshi_LightItalic.otf
        - asset: fonts/Satoshi_Medium.otf
        - asset: fonts/Satoshi_MediumItalic.otf
        - asset: fonts/Satoshi_Regular.otf

  assets:
    - assets/
